language: java
dist: trusty
jdk:
    - oraclejdk8


before_install: chmod +x gradlew

# Setup the workspace.
install:
  - ./gradlew setupCIWorkspace -S

# So the cache doesn't get repacked every time.
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

# Cache libs, as to improve speed.
cache:
  directories:
    # The libs is up to debate...
    #- ./libs
    - $HOME/.gradle/caches
    # But gradle is not.
    - $HOME/.gradle/wrapper